### PR TITLE
Set the remote_ip_check feature flag to true.

### PR DESCRIPTION
**Pull request by jkeck**

### CODE REVIEW

**Comment by ndushay** [comment]
silly question:  do you want to do this in a feature branch as well?

**Comment by jkeck** [comment]
I'm not sure why we would use a feature branch for this.

**Comment by ndushay** [comment]
I meant while you get the kinks out.  To avoid inadvertently turning it on in prod.

**Comment by ndushay** [comment]
Jessie needs to test something because he was getting errors for off-campus (?) IPs

**Pull request merged**
