### PR TITLE
Combine tests that use the same scenario setup

### PR DESCRIPTION
**Pull request by jcoyne**
This makes the suite faster since we don't have to repeat the identical test setup

### CODE REVIEW

**Review by thatbudakguy — COMMENTED** [review]
does this really make a difference? i kind of prefer the opposite; single assertions per spec makes it easy to tie the failure to what was supposed to happen. tests are a place where being redundant and even slow is mostly fine for me, within reason.

**Comment by jcoyne** [comment]
Yes, I think that fast tests help keep developers productive and prevent you from loosing focus on the problem at hand. For me, having a fast test suite is critical. Rspec points you directly at the line that failed, so I'm unclear as to how it would be confusing as to which assertion is problematic.

**Comment by cbeer** [comment]
Would chained expectations (`expect().to include().and include()`) or `aggregate_failures` give us the best of both worlds? Consolidating the test setup seems good, but it's also nice if the tests give us the full picture of what went wrong 🤷‍♂️

**Comment by thatbudakguy** [comment]
I like the chained expectations idea. That might also make the `Rspec/MultipleExpectations` cop happy.

**Review by thatbudakguy — APPROVED** [review]

**Pull request merged**
