### PR TITLE
Allow the item selector to initialize in the 'in progress' state

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Review by dnoneill — COMMENTED** [review]
Shouldn't this be in the accordion header partial?

**Comment by cbeer** [comment]
I kept it separate on all the other accordions. I guess I can easily imagine a scenario where a couple accordions might start expanded or something 🤷‍♂️

**Comment by dnoneill** [comment]
I don't think we have placeholders accordions for any of our first steps. I guess I am wondering is there a reason that expanded: current_step == 1 couldn't be moved the accordion header and not placed in multiple places and it wouldn't expand anything other than the first step?

**Review by thatbudakguy — APPROVED** [review]

**Comment by cbeer** [comment]
This gets us to consistency with the different starting states. When we have all the panels in place and want to refactor this, that'll be a good time to decide whether the first step is always the same as the initially expanded one or if there's some variation (or other benefit to being explicit)

**Pull request merged**
