### PR TITLE
Address issue with vestigial highlighting in the scan form

### LINKED ISSUE #579: Carryover from destination/date picker affecting the scan form
Side effect of the changes made in #491 - the yellow div is showing up in the Scan form where it has no content.

https://searchworks.stanford.edu/view/9083684  for example.

screen shot 2016-10-14 at 9 54 28 am

### PR DESCRIPTION
**Pull request by jkeck**
Closes #579 

`/scans/new?item_id=359415&origin=SAL3&origin_location=STACKS`
## Before
359415-before

## After
359415-after

### CODE REVIEW

**Comment by tingulfsen** [comment]
Is it worth adding a test for this new behavior? Otherwise it looks good to me.

**Comment by jkeck** [comment]
Ah, I had one I was writing but forgot to include it.  Let me make sure it is legit and I'll push it up.

**Comment by tingulfsen** [comment]
👍

**Comment by ndushay** [comment]
LGTM;  👍   (I am Naomi Dushay and I approve this request - hound hasn't signed off yet)

**Pull request merged**
