### PR TITLE
Refactor confirmation email template to split out versions for each…

### LINKED ISSUE #718: Reword request confirmation emails
### Subject line

hold, page, scan
> Request confirmed: "Title"

mediated page
> Request waiting for approval: "Title"

error condition (request failed)
> Attention needed: Your request could not be processed ("Title")

### First line

hold
> You have been added to the hold queue for the following item(s):

page
> The following items are scheduled to be delivered to [pickup library]:

scan 
> The following items have been queued for scanning:

mediated page
> The following items are waiting for approval. Items are typically approved 1-3 days before your scheduled visit.

error (bad library id)
> We were unable to process your request because the Stanford Library ID you entered (badidgoeshere) was not found in our system. 

error (patron blocked)
> We were unable to process your request because your status is BLOCKED. 

error (other)
> We were unable to process your request because of a system error.

### Title / call number block

> Title:  title goes here
> Call number(s):
>    *  call number 1
>    *  call number 2

If there is no call number, display `   *  (no call number)`

### Additional info

hold
> We'll send another email when your request is ready for pickup.
> 
> Request was placed:   Monday, May 22 2017 at 2:11pm
> Request will be canceled if it cannot be fulfilled before:   Tuesday, May 22 2018

page
> Estimated delivery:   Monday, Jun 15 2017, after 10:00am. 
> We'll send you another email when your request is ready for pickup.
>
> Request was placed:   Tuesday, Jun 13 2017 at 3:07pm

scan
> Title of article or chapter:   
> [content]
> 
> Earliest delivery:   Monday, Jun 19 2017, after 6:00pm
> We'll send you another email when your request is ready for download.
>
> Request was placed:   Thursday, Jun 16 2017 at 5:07pm

mediated page
> Request was placed:   Friday, Jun 9 2017 at 2:11pm
> Planned date of visit:  Tuesday, Jun 27 2017

error (bad library id)
> Try your request again using just your name and email:   https://searchworks.stanford.edu/view/11474214
>
> Request was placed:   Thursday, Jun 15 2017 at 2:11pm

error (patron blocked)
> Request assistance by replying to this email, or check MyAccount (http://library.stanford.edu/myaccount) for more information.
>
> Even though your status is blocked, you are eligible for Scan to PDF. You can request a single article or chapter, up to 50 pages.
>  https://searchworks.stanford.edu/view/11474214

### URLs
hold, page, scan, error
> You can see this request status online at http://requests.stanford.edu/pages/105683/status

... and this line appears if the user has a valid SUNet ID or lib ID
> You can also see and change your requests at http://library.stanford.edu/myaccount

mediated page
> Check the status before you visit, at https://requests.stanford.edu/mediated_pages/105249/status

### Footer
no change (contact info specific to library)

### PR DESCRIPTION
**Pull request by jkeck**
…kind of error or request.

Closes #718

### CODE REVIEW

**Comment by jkeck** [comment]
@dlrueda does error code U004 (privs. expired) come through as a usererr_code in the symphony response?

**Comment by camillevilla** [comment]
## Hold
>Request received: "The design of everyday things"
Stanford Libraries Requests <greencirc@stanford.edu>
Wed 10/10/2018 4:03 PM
To:Camille Villa <cvilla@stanford.edu>;
You have been added to the hold queue for the following item(s): Title: The design of everyday things
Call number(s):
TS171.4 .N67 2013 has been placed on hold.
We'll send another email when your request is ready for pickup.
Request was placed: Wednesday, Oct 10 2018 at 4:03p
Request will be canceled if it cannot be fulfilled before: Thursday, Oct 10 2019
You can see this request status online at requests.stanford.edu

You can also see and change your requests at http://library.stanford.edu/myaccount
Questions about your request? Contact:
(650) 723-1493 greencirc@stanford.edu

## Page
>Request received: "Edward II: the pliant king"
Stanford Libraries Requests <greencirc@stanford.edu>
Wed 10/10/2018 4:08 PM
To:Camille Villa <cvilla@stanford.edu>;
The following items are scheduled to be delivered to Green Library: Title: Edward II: the pliant king
Call number(s):
DA230 .H88 has been paged for delivery.
Estimated delivery: Friday, Oct 12 2018, after 10:00am
You'll receive another email when your request is ready for pickup.
Request was placed: Wednesday, Oct 10 2018 at 4:07p
You can see this request status online at requests.stanford.edu
You can also see and change your requests at http://library.stanford.edu/myaccount
Questions about your request? Contact:
(650) 723-1493 greencirc@stanford.edu

## Scan
Request received: "Edward II: the pliant king"
Stanford Libraries Requests <scan-and-deliver@stanford.edu>
Wed 10/10/2018 4:09 PM
To:Camille Villa <cvilla@stanford.edu>;
The following items have been queued for scanning: Title: Edward II: the pliant king
Call number(s):
DA230 .H88 has been paged for scanning. Title of article or chapter: Chapter 3
Estimated delivery:
You'll receive another email when your request is ready for download.
Request was placed: Wednesday, Oct 10 2018 at 4:09p
You can see this request status online at requests.stanford.edu
You can also see and change your requests at http://library.stanford.edu/myaccount
Questions about your request? Contact:
(650) 723-1493 scan-and-deliver@stanford.edu

## Mediated
Item(s) requested ("Canyon Cinema records, circa 1961-2009")
Stanford Libraries Requests <specialcollections@stanford.edu>
Wed 10/10/2018 4:14 PM
To:Camille Villa <cvilla@stanford.edu>;
On Wednesday, Oct 10 2018, you requested the following:
Canyon Cinema records, circa 1961-2009
Item(s) requested: M1681 BOX 1
I plan to visit on: Wednesday, Oct 17 2018
Check the status of your request at http://requests-stage.stanford.edu/mediated_pages/170/status You can also see the status at http://library.stanford.edu/myaccount
Questions about your request? Contact:
(650) 725-1022 specialcollections@stanford.edu

**Comment by camillevilla** [comment]
TODO:
-[ ] HOLD URLs for paid account users should point to library.stanford.edu/libraryaccount
-[ ] Subject: "We received your request for "TITLE""
-[ ] "We'll email you again when your request is ready for pickup"
-[ ]

**Comment by camillevilla** [comment]
@jkeck The last thing I'm having trouble with is getting the link at the end of `You can see this request status online at requests.stanford.edu` to use HTTPS. Any ideas / can we pair on this tomorrow?
https://github.com/sul-dlss/sul-requests/blob/fb8f85ea829812112098dd48a2965fac01c7f417/app/views/approval_status_mailer/approval_status_for_holdrecall.html.erb#L30

**Comment by jkeck** [comment]
@camillevilla happy to help look at this.  Is the issue that in tests it's `http`?  If so, I _think_ that should be fine.  Since we're using rails' route helpers here, we should get `https` in real `https` environments (like stage and prod).  Perhaps I'm miss-understanding the issue though.

**Comment by camillevilla** [comment]
@jkeck I just sent things over to @saseestone for final review. I CC'd you some of the sample emails that stage generated. Either way, I think it should get split to another ticket.

**Pull request merged**
