### PR TITLE
Allow mediated pages with no needed_date to show up under active scope.

### LINKED ISSUE #446: Items with no needed date do not show up on mediation page
Active and Archived scopes are based on needed_date.  If there is no needed_date the record does not show up under either.

### PR DESCRIPTION
**Pull request by jkeck**
Fixes #446

### CODE REVIEW

**Comment by cbeer** [comment]
I guess we're saying those requests never fall off the page?

`¯\_(ツ)_/¯`

**Comment by jkeck** [comment]
Yeah, I guess so.  If we define `archived` as the needed date has passed, and we allow requests without needed date, then they must always be active requests! :-/

**Comment by jkeck** [comment]
And I'm more than happy to let @jvine give her $.02.

**Comment by cbeer** [comment]
:shipit:

**Comment by jvine** [comment]
I don't have a problem with them being on the page if they are always at the bottom. Both Hopkins and PAGE-MP are pretty low volume - we probably have a year before we have to consider another solution for them.

**Pull request merged**
