### PR TITLE
[WIP] Create workflow for submitting a scan request to symphony

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by cbeer** [comment]
@jkeck can you take a look at this and see if I'm on the right track? If so, I'll start polishing it up with tests and reporting back to the user..

**Comment by jkeck** [comment]
:+1: generally looks good to me.  I don't have a 100% grasp on which callback we should be using in order to notify the user (and if we should be creating rows in the requests table for failed requests or not), but I think you will probably figure out the best approach when you implement reporting back to the user.

**Comment by jkeck** [comment]
I'm holding off on merging this in for the moment.  I'm concerned about deploying this to -dev (even though we could just not configure the endpoint) since we would end up submitting SCAN requests to morison for every other type of request as well.  Generally I agree with this approach and it looks good though.

**Comment by cbeer** [comment]
> we would end up submitting SCAN requests to morison for every other type of request as well

That's not the intended behavior -- it should only run the `SubmitScanRequestJob` on actual scan requests (and, if we want to disable that in -dev, maybe we should add a configuration option)

**Comment by jkeck** [comment]
Ah, I didn't notice the separate `submit!` methods in `Request` and `Scan`.

**Pull request merged**
