### PR TITLE
render page range content as html_safe fixes #813

### LINKED ISSUE #813: SCAN email confirmation showing html in Page range
The confirmation email message for SCAN requests is showing html in the "Page range" section of the email body.  Here's an example:

image

### PR DESCRIPTION
**Pull request by mejackreed**
Fixes #813

### CODE REVIEW

**Comment by jkeck** [comment]
Was the issue here that a user supplied HTML in their comment and we want to render that HTML on the status page side? (which could potentially be a bad thing)

Also, I think the original ticket mentions the content being in the email output, which I'm not sure this addresses.

**Comment by camillevilla** [comment]
It would be good to pair on this and conduct some tests in stage to verify behavior. My understanding was that HTML was being produced even though the user was supplying plain text.

**Comment by mejackreed** [comment]
Yep seems like a good thing to pair on. I'm not sure I even really understand what is happening in requests, so open to suggestions/pairs

**Comment by mejackreed** [comment]
Closing this, turns out this doesn't really do what I thought it did.

**Pull request closed without merging**
