### PR TITLE
Updates to request form styles

### LINKED ISSUE #94: Styling/responsiveness of initial "Request" step
* [x] Make "Just need a ..." an h2 with this context-specific style:
```
     background: #fbfbf9;
     padding: 0 10px;
     display: inline-block;
     text-align: center;
     padding: 0 10px;
     margin: 0 0 .5em;
```

* [x] Add a div around the h2, and move `class="separator"` to that div.

* [x] To make the line that appears "behind" the name, add this to the div.row that follows it:
```
     border-top: 1px solid #d5d5d3;
     padding-top: 30px;
     margin-top: -22px;
```

* [x] make the buttons full width, remove the right-align, and add a bottom margin
```
#scan-or-deliver .buttons a.btn {
     width: 100%;
     max-width: 20em;
}
#scan-or-deliver .buttons {
  /* text-align: right; */
  margin-bottom: 1em;
}
```

I think that's everything - the outcome should look like this at largest width:

screen shot 2015-04-29 at 1 39 20 pm

and this at smallest width:

screen shot 2015-04-29 at 1 38 19 pm

### PR DESCRIPTION
**Pull request by jchristo4**
Closes #94 

image

image

### CODE REVIEW

**Comment by jkeck** [comment]
@jchristo4 this needs a rebase.

**Comment by jchristo4** [comment]
@jkeck done rebasing

**Comment by jkeck** [comment]
@jvine do you want to take a look at the screenshots here?  The buttons don't appear to both be taking up the full width of the column as you're asking in the 4th checkbox on #94.  The screenshots from the ticket and from the PR look pretty different to me.

**Comment by jvine** [comment]
You're right, it's not wide enough. It looks like it's in the CSS, though - 
```
a {
+      .btn {
+        max-width: 20em;
+        width: 100%;
+      }
```

In the screenshot it doesn't look like the .btn font size is correct either, but I see it correctly in the current deployed version.

**Comment by jchristo4** [comment]
@jvine, @jkeck Looks like few added styles were missing after rebase. Working on fixing this.

**Comment by jchristo4** [comment]
@jkeck Fixed style issues and rebased

**Comment by jkeck** [comment]
@jvine look good?

scannable-responsive

**Comment by jvine** [comment]
:+1:

**Pull request merged**
