### PR TITLE
Preserve user values after validation failures

### LINKED ISSUE #319: Keep user values when error fails back to the form
When a request fails and redisplays the form, we need to keep the user-entered values. Example at Hopkins:  Select a different delivery library, login to submit, request fails, and form redisplays with the default delivery library selected. Same issue with multiple items selected - if the request fails, the form redisplays with no items selected.

### PR DESCRIPTION
**Pull request by cbeer**
Fixes #319

### CODE REVIEW

**Comment by cbeer** [comment]
If you have any ideas how to test this behavior, I'm all :ear:. It seemed unnecessarily tricky because:

 - in order to get a validation failure, it has to bypass the html5 + js validation
 - in order to check the results, we need javascript to populate the breadcrumbs..

**Comment by jkeck** [comment]
Yeah, that's a tough one.  The only thing that I can think of is using javascript (via `page.execute` or something like that) to add `novalidate` to the form in the context of these tests.  That may not be the greatest idea but I think it would allow us to submit the form required fields left blank....  I'll leave it up to you, I'm good w/ :ship:ing it.

**Comment by cbeer** [comment]
ok, I'll look into that and :shipit: if nothing good comes of it.

**Comment by cbeer** [comment]
:shipit: ?

**Pull request merged**
